spring:
  application:
    name: maroctbib
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: true
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply@maroctbib.ma
    password: dummy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 9091

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.maroctbib: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
    secret: dev-secret-key-please-change-32chars-minimum!
    expiration-ms: 900000
    refresh-expiration-ms: 604800000
  seed:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers,prometheus"
  endpoint:
    health:
      show-details: when_authorized
